
  CREATE TABLE "ADMIN"."ORDERTYPE" 
   (	"O_TYPE_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"O_TYPE_NAME" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "ORDERTYPE_PK" PRIMARY KEY ("O_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 
