
  CREATE TABLE "ADMIN"."ORDERSTATUS" 
   (	"O_STATUS_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"O_STATUS_NAME" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "ORDERSTATUS_PK" PRIMARY KEY ("O_STATUS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 
