
  CREATE TABLE "ADMIN"."ORDERFOODS" 
   (	"O_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"F_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"OF_NUM" NUMBER(5,0), 
	 CONSTRAINT "ORDERFOODS_PK" PRIMARY KEY ("O_ID", "F_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ORDERFOODS_FOODS_FK1" FOREIGN KEY ("F_ID")
	  REFERENCES "ADMIN"."FOODS" ("F_ID") ENABLE, 
	 CONSTRAINT "ORDERFOODS_ORDERS_FK1" FOREIGN KEY ("O_ID")
	  REFERENCES "ADMIN"."ORDERS" ("O_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 
